version: '3'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    healthcheck:
      test: ["CMD", "psql", "-U", "${POSTGRES_USER}", "${POSTGRES_DB}"]
    ports:
      - '5432:5432'

  minio:
    image: minio/minio
    ports:
      - "19000:9000"
      - "19001:9001"
    volumes:
      - ./datastore:/data
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    command: server --console-address ':9001' /data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      /usr/bin/mc mb myminio/${S3_BUCKET};
      /usr/bin/mc policy set public ${S3_BUCKET};
      exit 0;
      "
  hive-metastore-standalone:
    build: .
    image: hive-metastore-standalone:latest
    depends_on:
      createbuckets:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_DB=${POSTGRES_DB}
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - AWS_ACCESS_KEY_ID=${MINIO_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${MINIO_SECRET_KEY}
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_BUCKET
      - S3_PREFIX
    ports:
      - '19083:9083'

